### ISSUE TITLE
Do you used the  gpu for training?

### ISSUE THREAD

**Issue by monster-xie** [metehancekic/wireless-fingerprinting#1]
how much time for train this deep learning network? thank you!

**Comment by metehancekic** [comment]
Yes, we use 1080ti to train all the models. It takes around 8 seconds per epoch to train "network_200_modrelu_short" with the following parameters:

Batch Size 100
Training set size 38000

**Comment by monster-xie** [comment]
> Yes, we use 1080ti to train all the models. It takes around 8 seconds per epoch to train "network_200_modrelu_short" with the following parameters:
> 
> Batch Size 100
> Training set size 38000

theano is hard to use cuda gpu in ubuntu,what your version about  cuda and cudnn？

**Comment by metehancekic** [comment]
We are using the following versions for CUDA and cuDNN.
- CUDA  9.0.176
- cuDNN 7.3.1

**Comment by monster-xie** [comment]
> We are using the following versions for CUDA and cuDNN.
> 
> * CUDA  9.0.176
> * cuDNN 7.3.1

Thank you very much!
