### ISSUE TITLE
what is the preambles of wifi devices

### ISSUE THREAD

**Issue by josephars3** [metehancekic/wireless-fingerprinting#5]
Hi. I checked wireless fingerprinting project but I didn't understand the meaning of preamble of wifi device. What is the content of simulation file? Can you help me please ?

**Comment by metehancekic** [comment]
Hey, thanks for your interest. A preamble is a signal used in network communications to synchronize transmission timing between two or more systems. In WiFi protocol it is at the beginning and consists of 4 blocks (OFDM blocks). Simulated dataset is basically ideal preambles which passed through nonlinear effects and are injected AWGN. You can find the further detail on our paper. If you have any other questions, please let me know.

**Comment by josephars3** [comment]
Thanks a lot for your reply.
